version: "3"
services:
  workspace:
    image: composer
    working_dir: /app
    entrypoint: bash
    volumes:
      - .:/app
    tty: true
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      args:
        - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
